### ISSUE TITLE
Adding License(s)

### ISSUE THREAD

**Issue by jaeha-choi** [jaeha-choi/Proj_Coconut_Mobile#1]
Hello @seo-chang.

I think we should add a license to this project. We've already discussed this, but I thought I'd create an issue in case anyone else wants to make a suggestion, or discuss, etc.

I suggest GNU Affero General Public License v3.0 ("AGPL"). I need your permission to add the license as you've contributed to this project directly.

I think AGPL will be sufficient for now, but we could add an alternative license if there's enough demand for it.

Let me know what you think.

**Comment by seo-chang** [comment]
I agree to go with AGPL.
